server:
  port: 7001
eureka:
  instance:
    hostname: localhost # eureka服务端实例名称
  client:
    register-with-eureka: false # false表示不让eureka自己注册自己
    fetch-registry: false # false表示自己端就是注册中心，职责就是维护服务实例，并不需要检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 交互地址，查询服务和注册服务都需要这个地址
